version: "3.8"

services:
  gcref-pgdb:
    image: postgres:alpine
    restart: always
    container_name: gcref-pgdb
    env_file: docker-compose.env
    volumes:
      - ./postgres/postgresDB:/var/lib/postgresql/data
      - ./postgres/postgresInit:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  go-account:
    build: 
      context: .
      dockerfile: ./go-account/Dockerfile
      target: Dev
    depends_on: 
      - gcref-pgdb
    container_name: go-account
    volumes: 
      - ./go-account/server:/go/src/gf-ref/go-account/server
    ports: 
      - "7070:7070"

  # promotionsrv:
  #   build:
  #     context: .
  #     dockerfile: ./promotion/Dockerfile
  #     target: Dev
  #   depends_on:
  #     - pgdb
  #   container_name: promotionsrvcont
  #   environment:
  #     - MICRO_SERVER_ADDRESS=:50051
  #   entrypoint: CompileDaemon --build="go build -o promotionServer ./promotion/server/" --command=./promotionServer
  #   env_file: docker-compose.env
  #   volumes:
  #     - ./promotion/server:/go/src/goTemp/promotion/server
  #   ports:
  #     - "50051:50051"

  # promotioncli:
  #   build:
  #     context: .
  #     dockerfile: ./promotion/DockerfileCli
  #     target: Dev
  #   container_name: promotionclicont
  #   environment:
  #     - MICRO_SERVER_ADDRESS=":50051"
  #   entrypoint: CompileDaemon --build="go build -o promotionClient ./promotion/client/" --command=./promotionClient
  #   volumes:
  #     - ./promotion/client:/go/src/goTemp/promotion/client
  #   ports:
  #     - "50052:50051"